name: Release - Deploy

on:
  push:
    branches:
      - release

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 0
        ref: release

    - name: dotnet Setup
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.x'

    - name: GitVersion Setup
      uses: gittools/actions/gitversion/setup@v0.9.7
      with:
        versionSpec: '5.x'

    - name: GitVersion Execute
      uses: gittools/actions/gitversion/execute@v0.9.7
      id: gitversion
      with:
        useConfigFile: true

    - name: install cake
      run: dotnet tool restore

    - name: dotnet Cake
      run: dotnet cake
      env:
        GIT_VERSION: ${{ steps.gitversion.outputs.semVer }}

    - name: CodeCov - UnitTests
      uses: codecov/codecov-action@v2
      with:
        files: ./tests/.coverage/cov.cobertura.xml
        fail_ci_if_error: true

    - name: Build, Push and Release a Docker container to Heroku
      uses: gonuit/heroku-docker-deploy@v1.3.3
      with:
        email: ${{ secrets.HEROKU_EMAIL }}
        heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
        heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}